// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DYT.infrastructure.Models;

public partial class Task
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int StatusId { get; set; }

    public int TypeId { get; set; }

    public string Description { get; set; }

    public virtual Status Status { get; set; }

    public virtual TypeTask Type { get; set; }
}